/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeechToTextRouteImport } from './routes/speech-to-text'
import { Route as ObjectDetectionRouteImport } from './routes/object-detection'
import { Route as LivePhotoToolRouteImport } from './routes/live-photo-tool'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DouyinToolIndexRouteImport } from './routes/douyin-tool/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SpeechToTextRoute = SpeechToTextRouteImport.update({
  id: '/speech-to-text',
  path: '/speech-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectDetectionRoute = ObjectDetectionRouteImport.update({
  id: '/object-detection',
  path: '/object-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const LivePhotoToolRoute = LivePhotoToolRouteImport.update({
  id: '/live-photo-tool',
  path: '/live-photo-tool',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DouyinToolIndexRoute = DouyinToolIndexRouteImport.update({
  id: '/douyin-tool/',
  path: '/douyin-tool/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-photo-tool': typeof LivePhotoToolRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/douyin-tool/': typeof DouyinToolIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-photo-tool': typeof LivePhotoToolRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/douyin-tool': typeof DouyinToolIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-photo-tool': typeof LivePhotoToolRoute
  '/object-detection': typeof ObjectDetectionRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/douyin-tool/': typeof DouyinToolIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live-photo-tool'
    | '/object-detection'
    | '/speech-to-text'
    | '/douyin-tool/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live-photo-tool'
    | '/object-detection'
    | '/speech-to-text'
    | '/douyin-tool'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/live-photo-tool'
    | '/object-detection'
    | '/speech-to-text'
    | '/douyin-tool/'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LivePhotoToolRoute: typeof LivePhotoToolRoute
  ObjectDetectionRoute: typeof ObjectDetectionRoute
  SpeechToTextRoute: typeof SpeechToTextRoute
  DouyinToolIndexRoute: typeof DouyinToolIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speech-to-text': {
      id: '/speech-to-text'
      path: '/speech-to-text'
      fullPath: '/speech-to-text'
      preLoaderRoute: typeof SpeechToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-detection': {
      id: '/object-detection'
      path: '/object-detection'
      fullPath: '/object-detection'
      preLoaderRoute: typeof ObjectDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-photo-tool': {
      id: '/live-photo-tool'
      path: '/live-photo-tool'
      fullPath: '/live-photo-tool'
      preLoaderRoute: typeof LivePhotoToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/douyin-tool/': {
      id: '/douyin-tool/'
      path: '/douyin-tool'
      fullPath: '/douyin-tool/'
      preLoaderRoute: typeof DouyinToolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LivePhotoToolRoute: LivePhotoToolRoute,
  ObjectDetectionRoute: ObjectDetectionRoute,
  SpeechToTextRoute: SpeechToTextRoute,
  DouyinToolIndexRoute: DouyinToolIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
